---------------------------------------------------------------------------
--- Set of helper functions and libraries for desktop environments
--
-- @author Tom Meyers &lt;tom@odex.be&gt;
-- @copyright 2020 Tom Meyers
-- @module lib-tde
---------------------------------------------------------------------------
