require("tests.profile-scripts.bluetooth-status")
require("tests.profile-scripts.cpu-value")
require("tests.profile-scripts.hard-drive-value")
require("tests.profile-scripts.network-value")
require("tests.profile-scripts.ram-value")
require("tests.profile-scripts.temp-value")
require("tests.profile-scripts.wifi")
