#!/usr/bin/env bash

# MIT License
#
# Copyright (c) 2019 manilarome
# Copyright (c) 2020 Tom Meyers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# Custom git data
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# This file will parse the allowed commit messages and puts them in the commit-msg file
# So we don't have to remember the prefixes

ROOT_REPO_DIR="$(git rev-parse --show-toplevel)"

eval "declare -a $(grep "VALID_START_REGEX=" "$ROOT_REPO_DIR/hooks/commit-msg")";

INFO="# Allowed commit message prefixes (In the title)\n#"

for t in ${VALID_START_REGEX[@]}; do
    INFO="$INFO $t "
done

sed -i 's/# On branch/'"$INFO\n#\n# On branch"'/g' "$COMMIT_MSG_FILE"

sed -i '1s|^|MISC: \n\n|' "$COMMIT_MSG_FILE"


# SOB=$(git var GIT_COMMITTER_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# git interpret-trailers --in-place --trailer "$SOB" "$COMMIT_MSG_FILE"
# if test -z "$COMMIT_SOURCE"
# then
#   /usr/bin/perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
# fi
