name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Your issue didn't have any activity, automatically marking it as stale. If this was wrong please notify us 😀"
        stale-pr-message: "Your Pull Request didn't have any activity, automatically marking it as stale. If this was wrong please re-open it 😀"
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
